### PR TITLE
The push-processor Lambda can notify an SNS topic

### PR DESCRIPTION
**Pull request by acharp**
As discussed, only add a global sns_topic for the whole push-processor. Not specific topic for each output at the moment.

---

This change is [Reviewable](https://reviewable.io/reviews/humilis/humilis-push-processor/6)

### CODE REVIEW

**Comment by germangh** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[humilis_push_processor/meta.yaml.j2, line 47 at r1](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-KRgoKCF0qRVrC62ypRI:-KRgoKCF0qRVrC62ypRJ:b26pat4) ([raw file](https://github.com/humilis/humilis-push-processor/blob/a6ddf7adf3a482b40483ebb66f56319718ab2368/humilis_push_processor/meta.yaml.j2#L47)):_

> ```
> 
>         {% if sns_topic %}
>         meta_sns_topic:
> ```

There is no need of having a `meta_` prefix here. It was needed for the `input/error/output` ones, I can explain you why if you want to know. This would be simpler in my opinion:

```
sns_topic_name:
    description:
        The name of a SNS topic the lambda can use to send notifications
    value:
        # You can simply leave this empty meaning: by default there is no SNS topic
```

No need to have any conditional here. If the user does not provide the 

---

_[humilis_push_processor/resources.yaml.j2, line 16 at r1](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-KRgpdoS3zR-c9a6W81C:-KRgpdoS3zR-c9a6W81D:bfjoq95) ([raw file](https://github.com/humilis/humilis-push-processor/blob/a6ddf7adf3a482b40483ebb66f56319718ab2368/humilis_push_processor/resources.yaml.j2#L16)):_

> ```
> {% set meta_input = meta_input or {} %}
> {% set meta_network = meta_network or {} %}
> {% set meta_sns_topic = meta_sns_topic or {} %}
> ```

No need for this.

---

_[humilis_push_processor/resources.yaml.j2, line 186 at r1](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-KRgpfaYv2CF1awn9RzX:-KRgpfaYv2CF1awn9RzY:b-ct2km2) ([raw file](https://github.com/humilis/humilis-push-processor/blob/a6ddf7adf3a482b40483ebb66f56319718ab2368/humilis_push_processor/resources.yaml.j2#L186)):_

> ```
>                     - "ec2:DeleteNetworkInterface"
>                   Resource: "*"
>                   {% if meta_sns_topic %}
> ```

Simpler:

```
{% if sns_topic_name %}
...
{% endif %}
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6)_

**Comment by acharp** [comment]
I have updated the PR and acknowledged all your comments but Reviewable doesn't allow me to Publish without writing an useless comment. That's why you are reading this atm...

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-:-KRhF0oJKKjRb6bbQU9f:b6i924d)_

**Comment by germangh** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-:-KRhG2Lc3tBDVnLov-OI:bnfp4nl)_

**Comment by acharp** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[humilis_push_processor/meta.yaml.j2, line 47 at r1](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-KRgoKCF0qRVrC62ypRI:-KRhpcRZ9gQ8A_kLzx_1:b-896fix) ([raw file](https://github.com/humilis/humilis-push-processor/blob/a6ddf7adf3a482b40483ebb66f56319718ab2368/humilis_push_processor/meta.yaml.j2#L47)):_
<details><summary>

<i>Previously, germangh (German Gomez-Herrero) wrote…</i></summary>



> There is no need of having a `meta_` prefix here. It was needed for the `input/error/output` ones, I can explain you why if you want to know. This would be simpler in my opinion:
> 
> ```
> sns_topic_name:
>     description:
>         The name of a SNS topic the lambda can use to send notifications
>     value:
>         # You can simply leave this empty meaning: by default there is no SNS topic
> ```
> 
> No need to have any conditional here. If the user does not provide the 
> </details>
> Done.

---

_[humilis_push_processor/resources.yaml.j2, line 16 at r1](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-KRgpdoS3zR-c9a6W81C:-KRhpe2vzmCuDDPYE-Az:b-896fix) ([raw file](https://github.com/humilis/humilis-push-processor/blob/a6ddf7adf3a482b40483ebb66f56319718ab2368/humilis_push_processor/resources.yaml.j2#L16)):_
<details><summary>

<i>Previously, germangh (German Gomez-Herrero) wrote…</i></summary>



> No need for this.
> </details>
> Done.

---

_[humilis_push_processor/resources.yaml.j2, line 186 at r1](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6#-KRgpfaYv2CF1awn9RzX:-KRhpd81Y_1yoY9jGpYy:b-896fix) ([raw file](https://github.com/humilis/humilis-push-processor/blob/a6ddf7adf3a482b40483ebb66f56319718ab2368/humilis_push_processor/resources.yaml.j2#L186)):_
<details><summary>

<i>Previously, germangh (German Gomez-Herrero) wrote…</i></summary>



> Simpler:
> 
> ```
> {% if sns_topic_name %}
> ...
> {% endif %}
> ```
> 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/humilis/humilis-push-processor/6)_

**Pull request merged**
